/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
//IMPORT LIBRARY
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Semih Aşdan No: 20202022082
 */
public class SaleMed extends javax.swing.JFrame {
    FileWriter fileWriter;
    FileWriter fileWriter1;
    FileWriter fileWriter2;
    DefaultTableModel model;

    /**
     * Creates new form SaleMed
     */
    public SaleMed() {
        //For window title and logo.
        setTitle("Menu-Seyrantepe Hospital - Sale Medication ");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\pics\\logo.png"));
        initComponents();
        //To be able to make changes to the table.
        model = (DefaultTableModel) saleTable.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        MedComBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namePet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        illPet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        docPet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        medPet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sale = new javax.swing.JButton();
        yesButton = new javax.swing.JRadioButton();
        noButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        saleTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cost = new javax.swing.JLabel();
        saleText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        geliss = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kar = new javax.swing.JLabel();
        dataBut = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        medError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 255, 255));

        MedComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lisinopril", "Levothyroxine", "Metformin", "Amlodipine" }));
        MedComBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedComBoxActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\pics\\medic.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Sale of medicines");

        namePet.setColumns(10);
        namePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namePetActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Patient Name :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Patient Illness :");

        illPet.setColumns(10);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Patient Medication :");

        docPet.setColumns(10);
        docPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docPetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Doctor Name :");

        medPet.setColumns(10);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Select Medication :");

        sale.setBackground(new java.awt.Color(234, 199, 199));
        sale.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sale.setText("Sale");
        sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleActionPerformed(evt);
            }
        });

        buttonGroup1.add(yesButton);
        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(noButton);
        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Should the Patient be Registered ?");

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));

        saleTable.setBackground(new java.awt.Color(234, 199, 199));
        saleTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        saleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Medication", "Medication Price"
            }
        ));
        saleTable.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane3.setViewportView(saleTable);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\pics\\uc.png")); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        cost.setForeground(new java.awt.Color(204, 204, 0));
        cost.setText("0");

        saleText.setBackground(new java.awt.Color(204, 204, 204));
        saleText.setForeground(new java.awt.Color(0, 204, 0));
        saleText.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Total Sales :");

        geliss.setForeground(new java.awt.Color(204, 0, 0));
        geliss.setText("0");

        jLabel12.setText("Total Cost :");

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Profit :");

        kar.setForeground(new java.awt.Color(0, 204, 0));
        kar.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saleText, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(geliss, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(kar)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geliss, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saleText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        dataBut.setBackground(new java.awt.Color(234, 199, 199));
        dataBut.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        dataBut.setText("Import Sales Data");
        dataBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataButActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        medError.setBackground(new java.awt.Color(255, 255, 255));
        medError.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(MedComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel3))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(docPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(illPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(medPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(dataBut)
                                    .addGap(18, 18, 18)
                                    .addComponent(medError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noButton)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)))
                        .addGap(0, 176, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(illPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(medPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MedComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noButton))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataBut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jScrollPane5.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Window transfers.
        {Menu menu = new Menu();
            setVisible(false);
            menu.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesButtonActionPerformed

    private void saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleActionPerformed
        // Identifying files.
        String filePath="C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\pdata.txt";
        File file = new File(filePath);

        String filePathh="C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\cost.txt";
        File fileCost = new File(filePathh);
        String gelis="C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\gelis.txt";
        File gelisF = new File(gelis);
        String medFile="C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\medData.txt";
        File fileMed = new File(medFile);
        String bakiyeFile="C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\bakiye.txt";
        File bakiye = new File(bakiyeFile);

        int price = 0;
        String name=namePet.getText();
        error.setText("");
        //Pricing according to the drug of choice.
        int selected= MedComBox.getSelectedIndex();
        switch (selected) {
            case 0 -> {
                price = 24;
                if(!medPet.getText().equals("Lisinopril")){
                    //Error message if the typed and selected drug names are not available.
                    medError.setText("Medication Mismatch!");
                }
            }
            case 1 -> {
                price = 16;
                if(!medPet.getText().equals("Levothyroxine")){
                    //Error message if the typed and selected drug names are not available.
                    medError.setText("Medication Mismatch!");
                }
            }
            case 2 -> {
                price = 20;
                if(!medPet.getText().equals("Metformin")){
                    //Error message if the typed and selected drug names are not available.
                    medError.setText("Medication Mismatch!");
                }
            }
            case 3 -> {
                price = 40;
                if(!medPet.getText().equals("Amlodipine")){
                    //Error message if the typed and selected drug names are not available.
                    medError.setText("Medication Mismatch!");
                }
            }
            default -> {
            }
        }
        //To check that all boxes are filled.
        if((!yesButton.isSelected()&&!noButton.isSelected())||namePet.getText().equals("")||illPet.getText().equals("")||medPet.getText().equals("")||
                docPet.getText().equals("") ){
            error.setText("Please Make Sure You Fill All The Boxes");
         }  //Add the patient to the data where all patients are kept?
            else if(yesButton.isSelected()){
                  

            try {
                /*I am using FileReader and BufferedReader libraries to 
                    import data.*/
                FileReader fileReader= new FileReader(fileCost); //I define the file as filereader.
                BufferedReader br=new BufferedReader(fileReader);    
                FileReader fileReader1 = new FileReader(gelisF); //I define the file as filereader.
                BufferedReader brGelis=new BufferedReader(fileReader1);
                FileReader fileReader2= new FileReader(bakiye); //I define the file as filereader.
                BufferedReader brr=new BufferedReader(fileReader2);
                String bakiyee = (brr.readLine());
                //It prints the data on the screen for the accounting of drugs.
                geliss.setText(brGelis.readLine());
                String d= geliss.getText();
                int e = Integer.parseInt(d);
                int gelisTotal= e+(price/2);
                String f= (""+gelisTotal);
                fileWriter1= new FileWriter(gelisF);
                fileWriter1.write(f);               
                fileWriter1.close();

                cost.setText(br.readLine());
                String b= cost.getText();
                int a = Integer.parseInt(b);
                int totalCost= price+a;
                String c= (""+totalCost);
                fileWriter= new FileWriter(fileCost);
                fileWriter.write(c);               
                fileWriter.close();
                //Converting the data in text to intager data type.
                int g = Integer.parseInt(bakiyee);
                //Checks if you have enough balance.
                if(g!=0||g>0){
                    //Printing patient name, drug name and price on the table.
                    model.insertRow(model.getRowCount(), new Object[]{
                    namePet.getText(),medPet.getText(),price});
                    //Deduct the Cost for Accounting from the balance.
                    String x= cost.getText();
                    int y = Integer.parseInt(x);
                    String z= geliss.getText();
                    int v = Integer.parseInt(z);
                    fileWriter2= new FileWriter(bakiye);
                    fileWriter2.write(""+(y-v));
                    fileWriter2.close();
                    kar.setText(bakiyee);

                    fileWriter= new FileWriter(fileMed, true);
                    fileWriter.write(namePet.getText()+";"+medPet.getText()+";"+price);
                    fileWriter.write(System.getProperty("line.separator"));
                    fileWriter.close();

                    saleText.setText("Mr. "+name+"'s medicine is "+price+"$");
                    //Save sales to data.
                    fileWriter= new FileWriter(file, true);
                    fileWriter.write(namePet.getText()+";"+illPet.getText()+";"+medPet.getText()+";"+docPet.getText());
                    fileWriter.write(System.getProperty("line.separator"));
                    fileWriter.close();
                    //Blank value in text dump for new patient entry.
                    namePet.setText("");
                    illPet.setText("");
                    medPet.setText("");
                    docPet.setText("");
            }else{
                   medError.setText("Insufficient Balance");
                   namePet.setText("");
                   illPet.setText("");
                   medPet.setText("");
                   docPet.setText("");

                }
            }

            catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);

            }
                //Add the patient to the data where all patients are kept?
            } else if(noButton.isSelected()){
                
                
                try {
                    /*I am using FileReader and BufferedReader libraries to 
                    import data.*/
                    FileReader fileReader= new FileReader(fileCost); //I define the file as filereader.
                    BufferedReader br=new BufferedReader(fileReader);    
                   
                    FileReader fileReader1 = new FileReader(gelisF); //I define the file as filereader.
                    BufferedReader brGelis=new BufferedReader(fileReader1);
                    
                    FileReader fileReader2= new FileReader(bakiye); //I define the file as filereader.
                    BufferedReader brr=new BufferedReader(fileReader2);
                    String bakiyee = (brr.readLine());
                    //It prints the data on the screen for the accounting of drugs.
                    geliss.setText(brGelis.readLine());
                    String d= geliss.getText();
                    int e = Integer.parseInt(d);
                    int gelisTotal= e+(price/2);
                    String f= (""+gelisTotal);
                    fileWriter1= new FileWriter(gelisF);
                    fileWriter1.write(f);               
                    fileWriter1.close();

                    cost.setText(br.readLine());
                    String b= cost.getText();
                    int a = Integer.parseInt(b);
                    int totalCost= price+a;
                    String c= (""+totalCost);
                    fileWriter= new FileWriter(fileCost);
                    fileWriter.write(c);
                    fileWriter.close();        
                    //Converting the data in text to intager data type.
                    int g = Integer.parseInt(bakiyee);
                    //Checks if you have enough balance.
                    if(g!=0||g>0){
                        //Printing patient name, drug name and price on the table.
                        model.insertRow(model.getRowCount(), new Object[]{
                        namePet.getText(),medPet.getText(),price});
                        saleText.setText("Mr. "+name+"'s medicine is "+price+"$");
                        //Deduct the Cost for Accounting from the balance.
                        String x= cost.getText();
                        int y = Integer.parseInt(x);
                        String z= geliss.getText();
                        int v = Integer.parseInt(z);
                        fileWriter2= new FileWriter(bakiye);
                        fileWriter2.write(""+(y-v));
                        fileWriter2.close();
                        kar.setText(bakiyee);
                        //Save sales to data.
                        fileWriter= new FileWriter(fileMed, true);
                        fileWriter.write(namePet.getText()+";"+medPet.getText()+";"+price+"(no save patient)");
                        fileWriter.write(System.getProperty("line.separator"));
                        fileWriter.close();
                    }else{
                        medError.setText("Insufficient Balance");
                    }
                    
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(SaleMed.class.getName()).log(Level.SEVERE, null, ex);
                } 
            
                namePet.setText("");
                illPet.setText("");
                medPet.setText("");
                docPet.setText("");
            

            }
        else{
            error.setText("Please Make Sure You Fill All The Boxes");

        }
    }//GEN-LAST:event_saleActionPerformed

    private void docPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docPetActionPerformed

    private void namePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namePetActionPerformed

    private void MedComBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedComBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedComBoxActionPerformed

    private void dataButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataButActionPerformed
        //Importing a Sale Data
        
        //I give the file location
        String filePath="C:\\Users\\semih\\OneDrive\\Belgeler\\NetBeansProjects\\mavenproject4\\src\\main\\java\\main\\medData.txt";
        File file = new File(filePath);

        try {
            FileReader fileReader= new FileReader(file); //I define the file as filereader.
            BufferedReader br=new BufferedReader(fileReader);
            Object[] lines = br.lines().toArray();
            //I loop it to get all the data.
            for (Object line : lines) {
                String[] row = line.toString().split(";");
                model.addRow(row);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dataButActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Window transfers.
        {Menu menu = new Menu();
            setVisible(false);
            menu.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MedComBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cost;
    private javax.swing.JButton dataBut;
    private javax.swing.JTextField docPet;
    private javax.swing.JLabel error;
    private javax.swing.JLabel geliss;
    private javax.swing.JTextField illPet;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kar;
    private javax.swing.JLabel medError;
    private javax.swing.JTextField medPet;
    private javax.swing.JTextField namePet;
    private javax.swing.JRadioButton noButton;
    private javax.swing.JButton sale;
    private javax.swing.JTable saleTable;
    private javax.swing.JLabel saleText;
    private javax.swing.JRadioButton yesButton;
    // End of variables declaration//GEN-END:variables
}
